# Generated by Django 4.1.7 on 2023-05-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.UUIDField(primary_key=True, serialize=False)),
                ('command_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VoiceFingerprint',
            fields=[
                ('voice_id', models.UUIDField(primary_key=True, serialize=False)),
                ('voice_fingerprint', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='reg_date',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='name',
        ),
        migrations.AddField(
            model_name='voicefingerprint',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AddField(
            model_name='command',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
    ]
