# Generated by Django 4.1.7 on 2023-06-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_command_voicefingerprint_remove_users_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command',
            field=models.CharField(default='', max_length=20),
        ),
    ]
