# Generated by Django 4.1.7 on 2023-06-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_id_alter_voicefingerprint_voice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
    ]
