# Generated by Django 4.1.7 on 2023-06-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_command_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
